name: Test

on: [push, pull_request]

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install g++
        run: sudo apt-get install g++
      - name: Test - All *.cpp files Compile successfully
        run: ./test-cpp-compile.sh
